### 获取token
POST http://127.0.0.1:4222/api/v1/auth/token
Content-Type: application/json;

{
  "username": "徐振坤",
  "password": "111111"
}

### 获取当前用户信息
POST 127.0.0.1:4222/api/v1/auth/me
Content-Type: application/json;
Authorization: Bearer {{token}}


### 获取用户信息
POST 127.0.0.1:4222/api/v1/users/list
Content-Type: application/json;
Authorization: Bearer {{token}}

{
  "skip": 0,
  "limit": 5
}


